version: "3"
services:
  pickle:
    image: andrcontrol/server
    hostname: PICKLE
    expose:
      - 9000/udp
    environment:
      - PORT=9000
      - HOST=PICKLE

  json:
    image: andrcontrol/server
    hostname: JSON
    expose:
      - 9000/udp
    environment:
      - PORT=9000
      - HOST=JSON

  xml:
    image: andrcontrol/server
    hostname: XML
    expose:
      - 9000/udp
    environment:
      - PORT=9000
      - HOST=XML

  proto_buf:
    image: andrcontrol/server
    hostname: PROTOBUFF
    expose:
      - 9000/udp
    environment:
      - PORT=9000
      - HOST=PROTOBUFF

  avro:
    image: andrcontrol/server
    hostname: AVRO
    expose:
      - 9000/udp
    environment:
      - PORT=9000
      - HOST=AVRO

  yaml:
    image: andrcontrol/server
    hostname: YAML
    expose:
      - 9000/udp
    environment:
      - PORT=9000
      - HOST=YAML

  msg_pack:
    image: andrcontrol/server
    hostname: MSGPACK
    expose:
      - 9000/udp
    environment:
      - PORT=9000
      - HOST=MSGPACK

  client:
    image: andrcontrol/client
    expose:
      - 2000/udp
    ports:
      - 2000:2000/udp
    depends_on:
      - pickle
      - json
      - xml
      - avro
      - yaml
      - proto_buf
      - msg_pack
    environment:
      - PORT=9000